Game.create!([
  {title: "Fallout 4", platform_id: 1},
  {title: "The Witcher 3: Wild Hunt", platform_id: 1},
  {title: "Destiny", platform_id: 1},
  {title: "Metal Gear Solid V: The Phantom Pain", platform_id: 1},
  {title: "Bloodborne", platform_id: 1},
  {title: "Dragon Age: Inquisition", platform_id: 1},
  {title: "Call of Duty: Black Ops III", platform_id: 1},
  {title: "Dragon Ball: Xenoverse", platform_id: 1},
  {title: "Star Wars Battlefront", platform_id: 1},
  {title: "Batman: Arkham Knight", platform_id: 1},
  {title: "Fallout 4", platform_id: 2},
  {title: "Destiny", platform_id: 2},
  {title: "Call of Duty: Black Ops III", platform_id: 2},
  {title: "Star Wars Battlefront", platform_id: 2},
  {title: "The Elder Scrolls Online: Tamriel Unlimited", platform_id: 2},
  {title: "The Witcher 3: Wild Hunt", platform_id: 2},
  {title: "Dragon Age: Inquisition", platform_id: 2},
  {title: "Halo 5: Guardians", platform_id: 2},
  {title: "Rise of the Tomb Raider", platform_id: 2},
  {title: "Tom Clancy's Rainbow Six Siege", platform_id: 2},
  {title: "The Elder Scrolls V: Skyrim", platform_id: 3},
  {title: "League of Legends", platform_id: 3},
  {title: "Fallout 4", platform_id: 3},
  {title: "Final Fantasy XIV Online: A Realm Reborn", platform_id: 3},
  {title: "World of Warcraft", platform_id: 3},
  {title: "Diablo III", platform_id: 3},
  {title: "The Witcher 3: Wild Hunt", platform_id: 3},
  {title: "Undertale", platform_id: 3},
  {title: "Minecraft", platform_id: 3},
  {title: "Hearthstone: Heroes of Warcraft", platform_id: 3}
])
Platform.create!([
  {title: "PS4"},
  {title: "XBOX ONE"},
  {title: "PC"}
])
Tip.create!([
  {body: "Use the Quick Inventory Menu", game_id: 1},
  {body: "Holster Your Weapon to Run Faster", game_id: 1},
  {body: "Sleep to Regenerate Health", game_id: 1},
  {body: "Power Armor Can Be Stolen", game_id: 1},
  {body: "Return Overdue Library Books", game_id: 1},
  {body: "Get More Quest XP", game_id: 1},
  {body: "Keep Your Companion's First Weapon", game_id: 1},
  {body: "Certain Clothes Provide Better Vendor Rates", game_id: 1},
  {body: "Sort Items In Your Pip-Boy", game_id: 1},
  {body: "Plan your travels by looking for Fast Travel signposts on the world map", game_id: 2},
  {body: "Make sure you make a regular manual saves", game_id: 2},
  {body: "Selecting targets will help you to focus on one enemy at a time to thin out groups, but make sure you keep moving", game_id: 2},
  {body: "Keep your strength up", game_id: 2},
  {body: "Look out for Places of Power", game_id: 2},
  {body: "Pick the right class", game_id: 3},
  {body: "Team up", game_id: 3},
  {body: "Aim for the head", game_id: 3},
  {body: "Don't just shoot", game_id: 3},
  {body: "Pick up your loot", game_id: 3},
  {body: "Think carefully about the type of hero you want to be", game_id: 15},
  {body: "Why fly solo when you can join a guild?", game_id: 15},
  {body: "Upgrade your mount at the first opportunity", game_id: 15},
  {body: "Collect everything - because crafting is vital", game_id: 15},
  {body: "Learn how to fight and always prepare for battle", game_id: 15},
  {body: "Always Keep A Precision Weapon Handy (Hang Onto The Pistol)", game_id: 18},
  {body: "Almost NEVER Sprint", game_id: 18},
  {body: "Don’t Melee Unless You Absolutely Have To", game_id: 18},
  {body: "Don’t Underestimate The New Boost-Slide", game_id: 18},
  {body: "Establish & Play Your Class – You Don’t Always Have To Kill", game_id: 18},
  {body: "Don’t fret about specific characters and positions. At least for the first five levels.", game_id: 22},
  {body: "Understand the basics of the map and different positions.", game_id: 22},
  {body: "Look at the mini-map every few seconds.", game_id: 22},
  {body: "Try all the positions, but focus on one.", game_id: 22},
  {body: "Don’t get serious about jungling until level 20 (at least).", game_id: 22},
  {body: "Don't lower the difficulty—some fights are supposed to be hard.", game_id: 21},
  {body: "Don't worry which ancestral stone you choose at first—character classes aren't permanent.", game_id: 21},
  {body: "Save often.", game_id: 21},
  {body: "Travel with a friend.", game_id: 21},
  {body: "Try using a shield.", game_id: 21},
  {body: "There are no dump stats but some stats are more dump than others.", game_id: 23},
  {body: "Don't overdo the settlements", game_id: 23},
  {body: "Make a home", game_id: 23},
  {body: "Don't rush through the main story", game_id: 23},
  {body: "Get a good range of guns", game_id: 23},
  {body: "If you see a star, kill it", game_id: 23},
  {body: "Register favorite Aetheryte locations", game_id: 24},
  {body: "Keybind everything (keyboard & mouse users)", game_id: 24},
  {body: "Move out of Area of Effect (AoE) attacks", game_id: 24},
  {body: "Finish your hunting log", game_id: 24},
  {body: "Spend your Grand Company Seals", game_id: 24},
  {body: "Log out in a sanctuary or inn", game_id: 24},
  {body: "Do your story missions", game_id: 24},
  {body: "Avoid aggro", game_id: 24},
  {body: "Place your attribute points carefully", game_id: 24},
  {body: "Level multiple classes", game_id: 24},
  {body: "Don't sell spiritbound gear", game_id: 24},
  {body: "You get credit for tapped mobs", game_id: 24},
  {body: "Get your chocobo ASAP", game_id: 24},
  {body: "Choose a Class — They're All Pretty Good", game_id: 26},
  {body: "Avoid Playing On Normal", game_id: 26},
  {body: "Enable Elective Mode To Customize Your Controls", game_id: 26},
  {body: "See the Map? See ALL of the Map", game_id: 26},
  {body: "If You See a Door, Go Through It", game_id: 26},
  {body: "Pick Up Everything", game_id: 26},
  {body: "As Soon as You Can, Start Crafting", game_id: 26},
  {body: "Brush Up On The Story So Far", game_id: 27},
  {body: "Read Quest Logs And Character Entries Regularly", game_id: 27},
  {body: "Set The Game To “Blood And Broken Bones” Difficulty", game_id: 27},
  {body: "You Can Change The Difficulty Mid-Game", game_id: 27},
  {body: "Save Often", game_id: 27},
  {body: "Steal Everything That Isn’t Bolted Down", game_id: 27},
  {body: "Loot Every Monster You’ve Killed", game_id: 27},
  {body: "Turn The Music Off, At Least Sometimes", game_id: 27},
  {body: "Experiment With HUD Settings", game_id: 27},
  {body: "On PC, Turn Off HairWorks", game_id: 27},
  {body: "Explore Every Question Mark In White Orchard", game_id: 27},
  {body: "Visit Every Notice Board On The Map", game_id: 27},
  {body: "Find Places Of Power", game_id: 27},
  {body: "Keep Your Gear Repaired And “Enhanced”", game_id: 27},
  {body: "You Can Repair Gear In Combat", game_id: 27},
  {body: "Don’t Sell Off Your Rare Crafting Materials", game_id: 27},
  {body: "Torches Create Temporary Air Pockets Underwater", game_id: 29},
  {body: "Torches Break Stacks Of Sand And Gravel", game_id: 29},
  {body: "Torches Can Hold Up Sand And Gravel", game_id: 29},
  {body: "You Can Build Off Of Torches", game_id: 29},
  {body: "Signs And Ladders Stop Water And Lava", game_id: 29},
  {body: "Blazes Hate Snowballs", game_id: 29},
  {body: "Soul Sand Makes You Sink", game_id: 29},
  {body: "In Creative Mode, Middle Click Gives You The Object You're Looking At", game_id: 29},
  {body: "You Only Need Two Buckets Of Water To Create An Infinite Water Source", game_id: 29},
  {body: "WATER MAKES A GOOD LAWN MOWER", game_id: 29},
  {body: "Invest in the Luck stat", game_id: 11},
  {body: "Learn Railsign", game_id: 11},
  {body: "Dress your settlers", game_id: 11},
  {body: "Trade ammo", game_id: 11},
  {body: "Know your enemy: get the Awareness Perk", game_id: 11},
  {body: "Don't Underestimate VATS", game_id: 11},
  {body: "Rename your guns", game_id: 11},
  {body: "Retrofit your weapons", game_id: 11},
  {body: "Use power armour. A lot.", game_id: 11},
  {body: "Keep an eye on fusion cores", game_id: 11},
  {body: "Some companions will steal for you", game_id: 11},
  {body: "Make an Alt… Okay, Make Two", game_id: 12},
  {body: "Learn When Things Switch", game_id: 12},
  {body: "Use the Public Event Tracker", game_id: 12},
  {body: "Find Groups With Destiny LFG", game_id: 12},
  {body: "Use the Official Destiny App", game_id: 12},
  {body: "Start Doing the Nightfall", game_id: 12},
  {body: "Pick Exotic Bounties Wisely", game_id: 12},
  {body: "Wait Until the Last Minute to Buy Anything", game_id: 12},
  {body: "Study Up on What Xur is Selling", game_id: 12},
  {body: "Buy Heavy Ammo and Telemetries From Xur", game_id: 12},
  {body: "You Don't Always Have to Fight", game_id: 5},
  {body: "Try Different Weapons", game_id: 5},
  {body: "Don't Waste Ammo", game_id: 5},
  {body: "It Never Hurts to Lend Others a Hand", game_id: 5},
  {body: "Stick and Move", game_id: 5},
  {body: "Your race doesn't matter too much", game_id: 8},
  {body: "Patience is key", game_id: 8},
  {body: "Stamina and ki are super important", game_id: 8},
  {body: "Don't be disheartened by tough parallel quests", game_id: 8},
  {body: "Don't bother getting frustrated with the online fight", game_id: 8},
  {body: "Knock", game_id: 4},
  {body: "Enemies Adapt", game_id: 4},
  {body: "Destroy Enemy Equipment", game_id: 4},
  {body: "Destroying Vehicles Will Not Harm Your S-Rank", game_id: 4},
  {body: "Kill the Lights for an Advantage", game_id: 4},
  {body: "Rescued POWs Usually Have High Stats", game_id: 4},
  {body: "Fast Travel", game_id: 4},
  {body: "Interrogate Mother Base Personnel", game_id: 4}
])
