Game.create!([
  {title: "Fallout 4", platform_id: 1},
  {title: "The Witcher 3: Wild Hunt", platform_id: 1},
  {title: "Destiny", platform_id: 1},
  {title: "Metal Gear Solid V: The Phantom Pain", platform_id: 1},
  {title: "Bloodborne", platform_id: 1},
  {title: "Dragon Age: Inquisition", platform_id: 1},
  {title: "Call of Duty: Black Ops III", platform_id: 1},
  {title: "Dragon Ball: Xenoverse", platform_id: 1},
  {title: "Star Wars Battlefront", platform_id: 1},
  {title: "Batman: Arkham Knight", platform_id: 1},
  {title: "Fallout 4", platform_id: 2},
  {title: "Destiny", platform_id: 2},
  {title: "Call of Duty: Black Ops III", platform_id: 2},
  {title: "Star Wars Battlefront", platform_id: 2},
  {title: "The Elder Scrolls Online: Tamriel Unlimited", platform_id: 2},
  {title: "The Witcher 3: Wild Hunt", platform_id: 2},
  {title: "Dragon Age: Inquisition", platform_id: 2},
  {title: "Halo 5: Guardians", platform_id: 2},
  {title: "Rise of the Tomb Raider", platform_id: 2},
  {title: "Tom Clancy's Rainbow Six Siege", platform_id: 2},
  {title: "The Elder Scrolls V: Skyrim", platform_id: 3},
  {title: "League of Legends", platform_id: 3},
  {title: "Fallout 4", platform_id: 3},
  {title: "Final Fantasy XIV Online: A Realm Reborn", platform_id: 3},
  {title: "World of Warcraft", platform_id: 3},
  {title: "Diablo III", platform_id: 3},
  {title: "The Witcher 3: Wild Hunt", platform_id: 3},
  {title: "Undertale", platform_id: 3},
  {title: "Minecraft", platform_id: 3},
  {title: "Hearthstone: Heroes of Warcraft", platform_id: 3}
])
Platform.create!([
  {title: "PS4"},
  {title: "XBOX ONE"},
  {title: "PC"}
])
Tip.create!([
  {body: "Use the Quick Inventory Menu", game_id: 1},
  {body: "Holster Your Weapon to Run Faster", game_id: 1},
  {body: "Sleep to Regenerate Health", game_id: 1},
  {body: "Power Armor Can Be Stolen", game_id: 1},
  {body: "Return Overdue Library Books", game_id: 1},
  {body: "Get More Quest XP", game_id: 1},
  {body: "Keep Your Companion's First Weapon", game_id: 1},
  {body: "Certain Clothes Provide Better Vendor Rates", game_id: 1},
  {body: "Sort Items In Your Pip-Boy", game_id: 1},
  {body: "Plan your travels by looking for Fast Travel signposts on the world map", game_id: 2},
  {body: "Make sure you make a regular manual saves", game_id: 2},
  {body: "Selecting targets will help you to focus on one enemy at a time to thin out groups, but make sure you keep moving", game_id: 2},
  {body: "Keep your strength up", game_id: 2},
  {body: "Look out for Places of Power", game_id: 2},
  {body: "Pick the right class", game_id: 3},
  {body: "Team up", game_id: 3},
  {body: "Aim for the head", game_id: 3},
  {body: "Don't just shoot", game_id: 3},
  {body: "Pick up your loot", game_id: 3}
])
